---
collections:
  - name: community.general
    version: 4.2.0
  - name: community.sops
    version: 1.2.0
  - name: ansible.posix
    version: 1.3.0
  - name: kubernetes.core
    version: 2.2.2
  - name: community.docker
    version: 2.1.0
roles:
  - src: xanmanning.k3s
    version: v3.0.0
  - src: patrickjahns.promtail
    version: 1.14.0
