---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
configMapGenerator:
  - name: background-image-1
    files:
      - sound_wave.svg
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
