---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      # This is a common chart for manual config
      chart: /charts/kah-common
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2021-11-24T23-19-33Z

    nameOverride: "minio"

    env:
      TZ: "${TZ}"
      MINIO_UPDATE: "off"
      MINIO_ROOT_USER:
        valueFrom:
          secretKeyRef:
            name: minio
            key: root-user
      MINIO_ROOT_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: minio
            key: root-password

    args:
      - server
      - /data
      - --console-address
      - :9001

    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /volume1/Minio/.minio
        mountPath: /root/.minio
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /volume1/Minio
        mountPath: /data

    service:
      main:
        ports:
          http:
            enabled: true
            port: 9001
          api:
            enabled: true
            port: 9000

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918-ips@kubernetescrd
        hosts:
          - host: "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
          - host: "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
          - host: "minio.${XYZ_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
          - host: "s3.${XYZ_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
        tls:
          - secretName: tls.minio
            hosts:
              - "{{ (index .Values.ingress.main.hosts 0).host }}"
              - "{{ (index .Values.ingress.main.hosts 1).host }}"
              - "{{ (index .Values.ingress.main.hosts 2).host }}"
              - "{{ (index .Values.ingress.main.hosts 3).host }}"

    podAnnotations:
      secret.reloader.stakater.com/reload: "minio"

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
