---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
  namespace: default
spec:
  storageClassName: data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.55.55
    path: "/volume1/Data"
  mountOptions:
  - nfsvers=4.1
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 1Mi
