---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
configMapGenerator:
  - name: background-image-2
    files:
      - generated_3.png
generatorOptions:
  disableNameSuffixHash: true
