apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-ddns-data
    namespace: networking
stringData:
    ddns_data.json: ENC[AES256_GCM,data:8J3l7r16GrhNu+bQrYABGguxVZ/yfRkqIper5Viymhs3v+B2RvY1mKI7uR2pSoc2Mm8Ec1N7/92EvGr+vLSoDZGDrmJUng3MtBya5xQAd8+w6TBfGOEOcoci7dZMVr2lW/uVz2+lH4Lqr6u2rVYnx9NFFMhK06da//6L7rvCiMREv3PCEgqqh7a4sbLl5qJKDivO4qc7xMI=,iv:YsxJGMNxhZ34QdCmOPSft+ICQ30hF9KYEHY4yiPJ2As=,tag:FTchacLY1BOR1QTAsGhmeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NVg3Z3pWY2I2azF3MkNC
            ZEtmVjE5ZE45N2hldVFHRG5DTE14VDZCMW13Cm52Vnd6STVQNTc5bzRONlNTd1p0
            c3BBZmRsc0gxVzZBWWlDbm04MTc2cVEKLS0tIE90ZWI4TG5hZzZBNkluM2dxZU44
            eHZEZVE3RStKN0ZDVHl0ajU2MkVNNHcKOS6CgluE45Nsv4uPRFKx5/u5Zd7asJf7
            ZmYhyHT3PqKD2Cw4G+Y9Eqyem/RYtoRM/L9jTGYAET33jlwGcD6CcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-20T18:23:07Z"
    mac: ENC[AES256_GCM,data:FNutyXCLJAUojJwtb8INOtF2f7MAMIbRkTfPJi0fCDpA4muyuObs+o0nXrnMzacDO63c0IDh14jgIsXfvqtfgLCgqrJfm0rBb9LlOjMSctXQRqdf3SJZ0saKXIN1oFJO5/DZaLKJ2nTTDRB3jx4n0IonWk/UTIUXVLHXBDn6kr4=,iv:TYx8n+S7yzgEmm5OWjTu/FwI7GmbfsPcFlnFg4vYaVI=,tag:hKlytAyA1wRlPIFjjUUT5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
