---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: calico-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://projectcalico.docs.tigera.io/charts
  timeout: 3m
