---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 5

  values:

    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.18

    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 2

    env:
      TZ: "${TZ}"

    autoscaling:
      enabled: true
      target: blocky
      minReplicas: 2
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        # v1.24 will have loadBalancerIPs
        # see https://github.com/kubernetes/enhancements/pull/1992
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-tls:
            enabled: true
            port: 853
            protocol: TCP
            targetPort: 853
          dns-https:
            enabled: true
            port: 443
            protocol: TCP
            targetPort: 443
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - "IPv4"
          - "IPv6"
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_BLOCKY_ADDR_V4}, ${SVC_BLOCKY_ADDR_V6}"
          metallb.universe.tf/allow-shared-ip: blocky
      dns-udp:
        enabled: true
        type: LoadBalancer
        # v1.24 will have loadBalancerIPs
        # see https://github.com/kubernetes/enhancements/pull/1992
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - "IPv4"
          - "IPv6"
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_BLOCKY_ADDR_V4}, ${SVC_BLOCKY_ADDR_V6}"
          metallb.universe.tf/allow-shared-ip: blocky

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/ip-sans: "${SVC_BLOCKY_ADDR_V4}, ${SVC_BLOCKY_ADDR_V6}"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure, dns-tls
          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd

        hosts:
          - host: &host blocky.${XYZ_DOMAIN}
            paths:
              - path: /

        tls:
          - secretName: tls.blocky
            hosts:
              - *host

    metrics:
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
    prometheus:
      serviceMonitor:
        enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: blocky-config
      secret.reloader.stakater.com/reload: tls.blocky

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname

    tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"

    persistence:
      whitelists:
        enabled: true
        mountPath: /app/whitelists
        type: custom
        volumeSpec:
          configMap:
            name: blocky-whitelist
      certs:
        enabled: true
        type: secret
        name: tls.blocky

    probes:
      startup:
        spec:
          initialDelaySeconds: 30

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
        cpu: 500m

    valuesFrom:
      - configMapRef:
          - name: blocky-config
            key: config
            optional: false
