---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - certificate.yaml
  # - dashboard
namespace: networking
configMapGenerator:
  - name: blocky-whitelist
    files:
      - whitelist.txt
generatorOptions:
  disableNameSuffixHash: true
