---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-config-v1
  namespace: blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-block
