kind: ENC[AES256_GCM,data:N5C/E/NZ,iv:LxKByGKzuIGCcdV+q3wQqTvw85FSy6MzWThQuvMg2hE=,tag:fCnObNXq2I5wC2uPkd5SpQ==,type:str]
ansible_user: ENC[AES256_GCM,data:ZcXI7fWR6w==,iv:pDRxzkl8kH06MGD4f1eWVFcppO5z5oDaTWO0bv5oyvw=,tag:d+yAz+guI6yJM3L1YIP1EQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DtG6wrCw2TUZWQ==,iv:DrfnRp6qFy6+KsxtGoy8PZLyudNiinI3DDvJuMN2Mlg=,tag:C6FGl2HVDEC73vaUSJfZ9A==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 1739B455D8162E8ACC070B6C818FDD02AE117F11
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwTlN39ypZ1lAQ//XFgaLr1Gg970qnU4hx1k+y5HYA+hQa9MY0P1PY5ZlQmU
            I9dh9dWosb8pE40IY84nOKul6INAgj2e86IHS6h+GLKkd+/6X3ima61KQJUKEo6s
            N8QiCtZm9Obw3t3mpZvWD6Ok375UQngh1T1KF3Leru0eN4gMZh6ThUmRakhpRa61
            WbHcA3L8bH8SfmluukUT069SNj+LygiTErt1egY3C9iiGDnKnKRAJ7qsY6SoMmOW
            aIQ1l9Ez68e0W5UlMcu2WrnpO6YonssHKWY/y0+C/XMXY6ZjVvv7me7UH1BAPl4n
            CBP9NubCoTHgPixSJ2f9LiDh3ZMNwd8335QGPy4SRbSrvp1t3Nqdz475rVYs5dKg
            Ndnr29EOtxmuBjVSc+X/VVo8jGrjAWFRv+LI56LwSoWLBQd19n1E3TsrgTw/gIjd
            Q2joZk0NhLwG17Q6TxD6/Rut8ribc7/ItvmcOh2I2h4kqzTRAVcadryuBTY0BCVo
            OET/z84WSFwyoSs0Q15Cge9essIG9o6pc7U96r55GLxQiC71AmnqLGyT+ChTLudF
            6BCfVYuExo57or47u/hNRZDhLdDVSpx2pngoY/Fj85g767r4ylKArbeUxlUpUfvJ
            1XHDzg79sxCCJhvPdgjMh86Nn3BekvukJ+4AW7S8TL1qFsgk/6484eoH9H5hYyjS
            XAFe3KmU3RgJfl7z2lqQMqs0DLgp3bUSeb6xsiIvwajfVfykkMZj6cBfrDcG7KMP
            sYvYmfju2+qUQ4mmhMe847x/ZgY4Ij77g7Lv7PQP736wojZ0+dZkg9EZYqq5
            =Ljox
            -----END PGP MESSAGE-----
        created_at: '2021-11-27T16:46:28Z'
    -   fp: C3FF78E5BF483EE816D78FAD1A42C338D23CA1F3
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxRAF+S9s+QEAQv9Gakz55iRgAu++n3uD7h6UVaC/8uEUocn5WUrZ/Ikpju5
            kiOG8lmU7FARyyKna3c0nSvvEzSISwQV5+pWg+5OPLEmC7LrG4tombH8olNgc6CK
            kSjIKfF3y47W5Koi2vDuCfYAFjzjXqcTUAKAcJkVEyVa6CWSCSw0zz+4sAXQcDzm
            acxCqfgMVUzMS6J6kYF/PHpL27crYDZHKfHFRJpHC4AY21T5GE1GlfhRWIi25eyP
            t+qZFwVNHtZS209xBMHnMKbxO+BBGFTuyUbCKxsTnYFTSCYB8QXk52VIdwbSdAVJ
            hIFlUGXnHWIrlxxDNBXgYXE11nJvNIv1qhFSZi/KVXyWXe/Gd1bhGxJ1g6r0dq4s
            sS4YqRvop1dCqFDbE5wXG5gGfBsWZBRGOOgITCQzesLtKLRZmH4KUyB6zj4iLxiw
            AN72z11LLKYE7755MeYcO3p7N6U6L/aRdUW41BxvPmvFFs1xVTONgokNIoCWm5MR
            IVL9ePftKqQlSQnjC2yT0lYBybEIsjQX3bUJtTzFRYYLuNS4kFiY/l4iT8jCmmVB
            o73xCH+hxqvCGdGk4CxVoYrL9FfSKqwTNgoSAgfoio573ajPAgDLVkSQgSnbAFIG
            Pv4uVVJeww==
            =qxav
            -----END PGP MESSAGE-----
        created_at: '2021-11-27T16:46:28Z'
    lastmodified: '2021-11-27T16:46:28Z'
    mac: ENC[AES256_GCM,data:5YwLqUxBQQoEjfOkQmGAg5eMhROODZ4eTIUo3w133VR1JCtoMSTF/YaGGYIKlpN1kXDH9sPMwVxcW3dv4D9hoXlQtAk05aYxKKPKes0AeEAoQOBIcgueJn+YOwWkk9Ap6MvXnGbqroqZ7nzqDSQMBaDKDvRtPaeplXvrFh+9aYY=,iv:arQQKYy3g4BDoEY+QVvJHmi7g56h6QjD/9+wJu83FpY=,tag:6kJhOVdQs0Dq3T60iH6nCw==,type:str]
