---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: latest
      imagePullPolicy: IfNotPresent
    env:
      TZ: "${TZ}"
      ADVERTISE_IP: "http://${LB_PLEX_IP}:32400/,https://plex.${XYZ_DOMAIN}"
      ALLOWED_NETWORKS: "10.0.0.0/8,172.16.0.0/16,192.168.0.0/16"
      PLEX_CLAIM: "${SECRET_PLEX_CLAIM}"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
        - 5600
        # Custom Camelus Group(s)
        - 65541
        - 65536
        - 65537

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${LB_PLEX_IP}
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
          traefik.ingress.kubernetes.io/service.serversscheme: https
        port:
          port: 32400

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/instance: "bloop-xyz,bloop-quarky"
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          hajimari.io/appName: "Plex"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.tls.options: "networking-plex@kubernetescrd"
          traefik.ingress.kubernetes.io/router.priority: "150"
          # traefik.ingress.kubernetes.io/router.middlewares: "networking-plex-add-web@kubernetescrd"
        hosts:
          - host: "plex.${XYZ_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "{{ (index .Values.ingress.main.hosts 0).host }}"
            secretName: "tls.plex"

    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: 20Gi
      transcode:
        enabled: false
        existingClaim: nfs-media-pvc
        subPath: Videos/transcode/
        readOnly: false
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
      nfs-media-pvc:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: /Data
        readOnly: false
      nfs-media-2-pvc:
        enabled: true
        existingClaim: nfs-media-2-pvc
        mountPath: /Data2
        readOnly: false
      nfs-misc-pvc:
        enabled: true
        existingClaim: nfs-misc-pvc
        mountPath: /DataR
        readOnly: false

    podAnnotations:
      backup.velero.io/backup-volumes: config
      pre.hook.backup.velero.io/container: fsfreeze
      pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/data"]'
      post.hook.backup.velero.io/container: fsfreeze
      post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/data"]'

    resources:
      requests:
        cpu: 1000m
        memory: 1500Mi
      limits:
        gpu.intel.com/i915: 2
        memory: 4900Mi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.4.1
        loki: http://loki.logs.svc.cluster.local:3100/loki/api/v1/push
        logs:
          - name: promtail/plex
            path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
          - name: promtail/plex/plugins
            path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
        securityContext:
          runAsUser: 0

    additionalContainers:
      fsfreeze:
        name: fsfreeze
        image: ghcr.io/k8s-at-home/fsfreeze:v2.37-r0
        volumeMounts:
          - name: config
            mountPath: /data
        securityContext:
          privileged: true
