---
apiVersion: v1
kind: Service
metadata:
  name: classic-svc
  namespace: networking
spec:
  externalIPs:
    - ${LB_TRAEFIK_CLASSIC}
  ports:
    - port: 443
      name: http
      protocol: TCP
    - port: 80
      name: https
      protocol: TCP
