---
apiVersion: v1
kind: Service
metadata:
  name: classic-svc
  namespace: networking
spec:
  ports:
    - port: 443
      name: http
      protocol: TCP
    - port: 80
      name: https
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: classic-svc
subsets:
  - addresses:
      - ip: ${LB_TRAEFIK_CLASSIC}
    ports:
      - port: 443
      - port: 80
