---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ${CLASSIC_DOMAIN}
  name: classic-traefik
  namespace: networking
spec:
  type: ExternalName
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - port: 80
      name: https
      protocol: TCP
  externalName: ${LB_TRAEFIK_CLASSIC}
  selector:
    app.kubernetes.io/instance: classic-traefik
    app.kubernetes.io/name: classic-traefik
