---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.1.0.100-10.5.0.255
  METALLB_TRAEFIK_ADDR: 10.1.0.101
  NAS_ADDRESS: 192.168.55.55
  LB_PLEX_IP: 10.1.0.105
  PROMETHEUS_PROFILE_IMG_URL: https://avatars3.githubusercontent.com/u/3380462

