# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DWTBPfRZxCe57YA26gyegJTAhg==,iv:IKutd00lILoGA9VJMasI/vEnI3BZVpK5WsKbUHqJWx4=,tag:HtytzFMeDYtyzfp+//vAhw==,type:str]
    XYZ_DOMAIN: ENC[AES256_GCM,data:uooQ/oJ6+tcOU68K,iv:fd/PrC1PYB2D6OH6eNCjHdXA9DFG8EbXBPPNXPAHTbE=,tag:Coe92IcLiLao2/PFmvNvRQ==,type:str]
    CLASSIC_DOMAIN: ENC[AES256_GCM,data:cEu2HQv0,iv:38BMJyKc8h6hRgZua6SnvR10XWoiyymp3KTdLOYzjYw=,tag:3qyXZDeqS1gDXsTRFCIU/g==,type:str]
    SECRET_GANDI_EMAIL: ENC[AES256_GCM,data:lDkEFiDGEBdd,iv:uTlB+1ULVmjDgy9UkDwHHLbkvp2GTYFLXy+R9ClzosY=,tag:4Mb19bBinX9gylFPGdb7IQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:22RC6r9jGu99fV5QnLRgtXEb,iv:jKq0gtTfIXFFo7Egnnz6/KdrwPQ4ydDi/B0LjIXuDro=,tag:bkt+a+xN7U6eL2onjQqCdQ==,type:str]
    DISCORD_ALERTS_USERNAME: ENC[AES256_GCM,data:zDZxy8N2chkEbBFfGg==,iv:WhJk2J+Ax0OBKzjaM/L/yCNu4N+EYY3n8PZAqklTPxk=,tag:cgmlaazp7c3XgKxoOpKkIw==,type:str]
    DISCORD_ALERTS_CHANNEL: ENC[AES256_GCM,data:R9DBxQBqk75nYlKHKv1/1g==,iv:er8d9MeQgrTT37cYSf+sq4w1ou2iC8Pyg4vSGvNNvyU=,tag:kb7TxiGXRySSHBkVNxvK1Q==,type:str]
    BLOOPNET_URI: ENC[AES256_GCM,data:Ulav4HPFuM8ZtXObFP5I,iv:BUnZf1RPMmKlJ9U6IKcSVoyfHNtvOkLrr1/CsBKzNBM=,tag:ozkeJZ06fOxriCKjl0NQZQ==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:sw+OF6sX6uItfJcJgAlRUPDk5Jguov8xPqsRsg4kOq8dFnade4Ed86As4O/oK2XsvaYGCZuq1qt9hMMWIVq3CCS8lE/ITnDXGWKRtysAYksQkHRSnMG1iBTjUBV7c1sHSp1A93iDFIhOikRJPL6hqVOAi1qEf8jr,iv:/i9uPElaLcWzw0eYNY0GNesovtKlx05D0pSg/oepuOw=,tag:Bxk3cMJJQidtnShIWfoiDg==,type:str]
    SECRET_SENDGRID_API_KEY: ENC[AES256_GCM,data:39MgiQyaZnMXXNzBf9XEWasSnQaM5aiwXQ4xkzh9X9L9G3A1GBUbTpjR/GiF/n1Bj6Jm+jTLTsnakXfbydGa02u8ejrB,iv:ORd52V/WtFWuSolRk5dAvUbnF+OcpX8TzciYO/8/JD4=,tag:/ZMtt4RlEVfXN/il3j/jBA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Q9MJaNKa+1IvYiPPgyoECHV6TY3C4B4PjRQukDnBwUBvWBph,iv:UtIVf1H5bU7XT8MW/fRZiv1HVbbNAvt3eAQdJqSrBLA=,tag:twwK8xDKpbcOvhIiYDVxWw==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:nt8jlHatn+tcRvvIwaM18wLWXEkFKQrtd7M+Jd4N0Fa2JUgyVLcW7riI1TBzcH5S/OQ=,iv:RjvHzsg8yZ+wvUwFDtwWFp2H/ZoDykyNfkOQLpWZ1wo=,tag:jWS1ByBk6jNw9lntc/nqhg==,type:str]
    AUTHENTIK_S3_SECRET: ENC[AES256_GCM,data:nnSXhRGu4KYYfHfi3wN1o4O40ufPUVUBXrJsl8Svwg553qzQ,iv:3ecv5FBmh5hV17J/T+UEFuJFrEYB3OHEB7J88BqQY9Y=,tag:aKDhFH/SjAVfIP6q051IdA==,type:str]
    AUTHENTIK_S3_ACCESS_KEY: ENC[AES256_GCM,data:ImD8NHTbEsIaNguLeb7yQ8jiMZ4+fkActGXL3743ssRJxNhl,iv:NDdC2QvhNYjcyqbLNISbpC/dvGkM3HPn+oNgN1fV0o0=,tag:2fiB7l9HJnENXZOaqTj6vw==,type:str]
    KEYCLOAK_USER: ENC[AES256_GCM,data:Ul24ZWI=,iv:lJ+gK2mencyblbmjGanbgFo1j1ptcyyxCtn1FCXo8Do=,tag:+NUTEO/h6dCkqblHiOKlhQ==,type:str]
    KEYCLOAK_PASSWORD: ENC[AES256_GCM,data:lcCbeCyFV4hIFIOV752n6cYW6CoGwo+Sy1/yfpv6vdIxEjog,iv:ifzkjf9l+H64ToaIg9ZcdQpD2qOmiXuLGnM0jbcCcVk=,tag:nETkzXM0bzER5Ydkc1XzwQ==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:6DrpPZduHqY=,iv:IENOhK8E7vjGIBoeFlz7zAdZA4U9Tl+ntLhPGibxQko=,tag:WWOveYHWrGWSlq0yr/49WQ==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:H6ZKo3b4+rA=,iv:aFsfouUpV9Ty21hjPPhF4+0Y5AVB4kN5hwLVhZGd+jI=,tag:eT3S3WWW1F8+VERJaEbl2Q==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:+SVT5Sc4W5y2YiwpO/sxuNSNgh1WjFL9cCU/Svn3rzm1WSBk,iv:jV20RXY2j7idkS2QTFpPxJ+VH7zjz4u7IHPFS+DIPXM=,tag:UX+OqpKbSoWapURZrXgMRA==,type:str]
    SECRET_PLEX_CLAIM: ENC[AES256_GCM,data:JK+E1ssQh6tnPayX0vEouKtm/7A=,iv:jpWDd1GmqV1fwBKzXbce5kY+RdiWlScMefvnmSZ1gAA=,tag:mAQAQ7+5Lf6qnw46QUQOIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbFZTd1luYWpLM1B3NlE5
            d2YxaXZPaElrWEZIQ1IwVUdyS0M3cEVVRVNRCmZaanN0bFpvcUMydHhHejZDdkdW
            THQ1MkYrbDhGYjlqZFkwVExCeGNHbXcKLS0tIHI0SFprVXhIMDZmb0JRVFNYQWtV
            TGZCZ1N3MFBVYVFBV3poQ3Y2dnlXTHMKW+9BCSEMgojQtMVbp7bAY0yskPuFxumC
            ubH7qoYr9aE6rNbSWF4rynaDRSTnZH44CYmaw4RZVR+BRUkdoOxoiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-12T23:51:15Z"
    mac: ENC[AES256_GCM,data:+1SnHKBsgpiYEt9Z1rEq1gwNkPpzsrfVmLM0s0neyCtb8kpGxlKnd4io5nTLIDZa/3iRtBFLJL/PUCwGnDSqcWgVyXNK26bRb0dh5xFU36lrOLXKIE8cedE/r+qd7vyWDj4W7LAYDPxXiGB6kmricALv63EJm1eXJHjWuNt3dJc=,iv:bQO+QwxKp9KvPHUmfxxF7lIgRZVk/tzhe0cj3lnZGIg=,tag:zlqLNgHoewqWjGbhg51org==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
