# yamllint disable
apiVersion: ENC[AES256_GCM,data:gyw=,iv:i0/2cK/7XuDsvqmmdul322ESH8z73KKpi+GmQuocgn0=,tag:sRqeiJpmz4WdAtWf9g1XLg==,type:str]
kind: ENC[AES256_GCM,data:kzZaYvZs,iv:GgHTugpfm6RdD4kSdgUFbtjlXY80zIzcOf5gSE93L0Y=,tag:rdRde9TW0ghmvaIc5ZFk1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LJpAYGfTRvET89bs7Ms0,iv:8ry8iW2RkIu9muTrhdg362oD/CYyW3JGO4i3UO+gR4w=,tag:Vaj7LEG4LAH7ffo5pJGFUw==,type:str]
    namespace: ENC[AES256_GCM,data:bkrdI6qvurO64Sc=,iv:2AflpRVjRQ4dvc6zbCwcKylb6kOsRWoZ7hHbR21Uz/4=,tag:4hor/6GcjqxOE/D1u/Bdlg==,type:str]
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:V5JaByQhBd0hQxa0fn/f8Y0=,iv:QrXpj7Ss04THsD9WTN7iRxAdpRFygoVvNh/6Kl3LQWg=,tag:wB8sv+OFd7IX7DEEX4mXZQ==,type:str]
    SECRET_GANDI_EMAIL: ENC[AES256_GCM,data:kKkdNJtAPYUf,iv:ikWP0ehihrJ6Wo26plPLjhb5EZDltwQEd3A/Z6XQtPU=,tag:RQBnGSbtDfs+xKWFlz45yA==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C3FF78E5BF483EE816D78FAD1A42C338D23CA1F3
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGLAxRAF+S9s+QEAQv3ZBm0/+ICOsdzdeyx6sq5XoTkLlueR4Xe9cOycmLAf/+U
            JNY0LdkALCWwhYkM+yvb1Zmb6LbamWWg1NIqQqw3Cf6GhYu9geiqdl41kYNkU9yR
            jNOm9Ct7lSfVo0s2Y5YTue5xjuDlon/0SbOebvwA4NevMDC4SwPdW78F7eipco2u
            lbJ5NqHXe7KyP2dCSFud2WmZVRMYXEv4rrOnxh7PVrLJtCg/oy1i9YWSjryb3x5S
            bCvjdCkAgevi/KohJiXbQrMxjHMyEXEQas6CMXl3YRy/09VebjFhteeqOMI69F1W
            ujaOeNOh1Gng82MKa/GigVhoYYw/egdl1kR7J7A6KzLo5ukOBEsafq0o4AUDTGZV
            ZMWUwQTFqq25jS8vjpQsPnsHhC9tDED+uoS2KHqltFMHvaX9/A95nP6tzmzBco3V
            uX/DUj0C5ew9EDCS4nj/+SMXgYNqSMKMWdGSsjZCnZza5pJNo/FYeA5n/ImcYA0S
            LdCLpCtXS0eiUzUj8bHSWAGQ+PhVksMlNF4MjD0akGsdxSSZO+XyCzMRpUqeE2OA
            jruoJ+n+WNxuYaITM/4ajkOeTlnlOMU9cvneGRTQFz26sQGcx0miQefYKdJsG+2N
            RvyI16FnsKA=
            =3Hbn
            -----END PGP MESSAGE-----
        created_at: '2021-11-14T04:09:59Z'
    lastmodified: '2021-11-14T04:09:59Z'
    mac: ENC[AES256_GCM,data:4FNvBlntJKDuvCSM5lt9Q8XF3OLEskxr2Jv8KzjYn+xXLT9NEn6LUWX2KkszoDO1pNZ2g0H5hN37lOY5e5MXsIfHvC4zptekjJP4hxpC81yEUJRlT3Q6dU0XbA9MYjXTBQekuBDUOiAmlSd5YwmkbTUjr7igK7qap9QM0wHzzbw=,iv:IeqfUlZnORbu+GLf7gzwLBmnT6JO8ReMmdbalffv2xc=,tag:/3ACmF59oDBZxSBmalPBLQ==,type:str]
