apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fKfqVTXwnjRwRX4p9WVZ27Q=,iv:2+GrF9iq7YB18OuMpNAue0662gkEWfvNVRq3Ehykmts=,tag:1B+qkNPJSM0ZvoeNB8Frgw==,type:str]
    SECRET_GANDI_EMAIL: ENC[AES256_GCM,data:ef9dIV7LMaNL,iv:C22MW3pLv6E12Bke1zGZ9tqEc/B0zYo4squ9DxKT2iM=,tag:s9akBJilr0dbFBIAYiJvlQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:wzKiYYfB7jMTp79kZbF0X78o,iv:e8kx/3lydOBE3vf8TQGT/2rWH+kxWIW9EUorihRSWsQ=,tag:VXGG08EF9n0OAAnSADok3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-11-27T17:36:16Z'
    mac: ENC[AES256_GCM,data:ZUTnbUcar+nFzgecellBI9pEPoUC5C0nMIYragcwuihTun6PW2iMHwsFJX39FFzexdaAKGRoz16GIurvipfrknqLqRZ/btDRxBQ8id/oZubH8zVviAxn4LNtREQj/SI/Fbtva0igWNf16vfCVVUNlKvyEOVP+Zn39L5gWtDg4Cw=,iv:krkz+2b7sPXSLG9lMPS5v8l00CMdr20px90X2VDX6TY=,tag:4pJv8Nqmjl/0VvRJIPgJLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.4.0
