# yamllint disable
apiVersion: ENC[AES256_GCM,data:m00=,iv:3K9h0SLQQsuHQUC1UBj5AhK/+BG1SLiuZRJv4/Wn+9U=,tag:R5gw6YclCTpwnYChNFQIjw==,type:str]
kind: ENC[AES256_GCM,data:HQcxozwT,iv:WH33oGv+XF4Ivu1TKnv+J9/XpyRC/LQm60DHfjLLFK4=,tag:lKm6GW8DSvVvo80w8DVjNw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:huuTiMroQpbx0/SOwxVe,iv:ADpcGY144VXY2q0O4l8rwTcQUJNepWtxvO3sHx5QyzY=,tag:8XyXX1qs2eunErn57U5MGA==,type:str]
    namespace: ENC[AES256_GCM,data:O4mOkFOwO/NifCA=,iv:v6iVELLOnszXLXM2eKb1qFuQNrY8PLSf90tutt53PSY=,tag:WXhD2teY097c4gnITaqE3Q==,type:str]
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mrVOF9ZIGWJBbOtTyV5UiQg=,iv:QR+cJuvhwBPFjv0VZ+CaayUs7IJWFYEiU6YbaEGkBRo=,tag:3tePxsc/JsTFNAEa7H/Brw==,type:str]
    SECRET_GANDI_EMAIL: ENC[AES256_GCM,data:/pBZuo/AFmG9,iv:cGUcEeZg+XwF0ll3b6QFVNhYtqfaGv+VETsdevgr2bk=,tag:vEP+e1roSeiuGKjwdYy+aQ==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C3FF78E5BF483EE816D78FAD1A42C338D23CA1F3
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxRAF+S9s+QEAQwAjuL4qQ60JN7Tz/zFxJXix1TGYTYjyOsnFLzL9/zBOY3A
            TRIXJVEAHkcrGTFCN4AGOwIcpkzKWCJul2mKj7J5wrqwPBzpAy+sEB7EA1MngNlQ
            nYzMKMtcUdtLk4lxm1Mt35jiwquj978Z08LviYeqNPCK1F07ItakACBXSlf95a9Y
            wsMpWpRYY3nq+wxQ8M7JDja81TvuV3XxUN3wgLE0NJLGbQzVdCMIKR6xexmRvXaY
            Y2R76PhT5fCL2i/HRsBHsSM19WSelzLI9m9s3k9NaZE1jsTDt8yxp76oZc2tdHAT
            ans77vKQrD5KW949pB2853fjRbf/zr+ejxht6okO2qRiUXa39CQd6gdCfmme4P9y
            rXXPDxz9+kEwzrdoPBye0//Ll501Yl1VGGZK1am3rlEre8EN9pj+Jp0ZSYwf6fJ4
            PLnEH1Ynki1KCsgXaBMJgt/95pD100uwOaeUn/1WwjNSb2zRK/I3+qj4iyf4Y2HR
            736b8+YNpQNMpKwplZSM0lgB1ecr+P19iLTfJYYz4MiHInikXuVdI1zhwOwrzSZN
            mHI8XjAI0gO9QaGjIXcL5BCiFRCLDsQuuFLvogd08WjvaZprUFEbw7+WAIdDB+NC
            cwonpfJIq2xT
            =Xqkx
            -----END PGP MESSAGE-----
        created_at: '2021-11-13T23:02:27Z'
    lastmodified: '2021-11-13T23:02:27Z'
    mac: ENC[AES256_GCM,data:KNxr4AmBozdFxLNPTzYxjJWcP/R++lz1rJMkvaJAHsCxG9mH9vZCeTmVrQIl0Y1+i1yMtrewh8mnmfCllvqK1fESEugABL/VEafeMrc31zFJnH8Ly+BhuoCtSH/kMGiyOck1VnH4tFvtiGaKg/4oNwPoHkUPu1c5thA9eUq9XNM=,iv:5VXgW79LRxuTjux3sk0J8sa6mqOhy+nUaZDo6Go5umg=,tag:cuTam8sfTY3OVuhJTerHcw==,type:str]
