# yamllint disable
apiVersion: ENC[AES256_GCM,data:sw4=,iv:rPoHxKiJ3BIGttLtfeq+Wr6VKnkoDqvpT/0zJT2nYuk=,tag:8aW2X8+DBXZKWnPX/1CkSg==,type:str]
kind: ENC[AES256_GCM,data:kVYMspfv,iv:uwl91mnPsYtn+X7UW7t7TIzozljVUtA0jsdsEfOyskE=,tag:MXvgWU/N5FSSW38nwSeQRQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UgIgt4AWK+7nqpBBFedn,iv:JWRVZSBwynnmaIaNY6O5o0epprfOdc1tD1hl+bz74X8=,tag:MQBlPCbWMK0CVma2cA27Xg==,type:str]
    namespace: ENC[AES256_GCM,data:3LcO89197bHfxSA=,iv:jnb0IE7F5hnFUMNfoolEVzEhP792xMccJc22moj1r/E=,tag:qbMzScFVsEmb4lT9xufl8Q==,type:str]
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3/EqCkvKEZpMhccEtJCWOfY=,iv:DNuvV9gL63B+2qiTfzG8x7jyaj9n8fpQBT4C0JhHoyo=,tag:/RwuX/J4VPJXWzzSLqrxfw==,type:str]
    SECRET_GANDI_EMAIL: ENC[AES256_GCM,data:Zl3LMQ2ieaF/,iv:2MyJd4yEAXG1VcRZQpUoeFpKYAYyJ9+XmfCIsVj9rVs=,tag:RQvLjV8rNsPSjw8D0uak6w==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C3FF78E5BF483EE816D78FAD1A42C338D23CA1F3
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxRAF+S9s+QEAQwAthCt1jTQ0+292RYbq7VfDusxDIX6eI8I/5kfkb01iQmI
            NOgosu9TGo1LyBgOkJlnc9tZu5TYtBqEYALVob+2K/Uus1RL90RJOPuQ38kcD+uh
            0etYLYfXqPl5SUXQz2VyP/HqIz069Tjlpz0ZgxY/iBUS2XaP1UwUvVueoUxbE/4o
            h+kYtUyT3gK2xfSnLe/AIKwCnh0/j2n7f3OzWvoOpnvc6qr4ewe8NOnlwEKuGuDn
            KmeNcvj8OpweLJFECIa+u5sKXvGjWh2K2AQHeo1lGek3Xe8hIbqsylUNSMOeU8mA
            tBMm9Lp2B5OlhAsWbinOPJJ3Uib232/Eqx0Ey/B4ttbd3RZIp/8b1MoG0kyo9AFv
            5Sc2QVFLYGbxmzkamwLQOuxpSqQZzYtgAnzetjsa72IQgOZjwbSPAwpiaoeNXcEV
            15UZaXzoExs+00Qvxe13rt6gUsbZDx+EkjWvfe5YbCbBSDlvTmKNtL8BJtgMxtl5
            iNqS3PmKz0tyg0Cn9X9O0lYBlompbJjksVwAihQDWuYwCBB6cdv8VtrHDxx00y0h
            K/98nlrJ/wJozqXCE1D3g2e1efLVIPbjKPtqMGwkqY5GL8WR1wbMe2MBAdvpZt23
            e4RWy3e5ng==
            =4DfK
            -----END PGP MESSAGE-----
        created_at: '2021-11-17T03:42:43Z'
    lastmodified: '2021-11-17T03:42:43Z'
    mac: ENC[AES256_GCM,data:ssY72sxArn7q5EWQr350EkXm/WKnXGsP/lEXGgxYVI2FteRmnAQDGXGrXDvX8rXsUBPv7OoD0p+ASOKjY2Y3fLwLIOZxZPyXMIRTD+UQhg4/juaAr0hsedxocX1wWgcy/uX0m0YU9GofTzB8YzFbBUwaL38gOc+EEhRHd1uMQaA=,iv:U703c6MYVoXaK+1+rbRNLACyPoycKn8QGJzG9HsjsMI=,tag:LQp9F1A79hCGaoGi2DxVfg==,type:str]
