---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.1.0.100-10.5.0.255
  METALLB_TRAEFIK_ADDR: 10.1.0.101
  NAS_ADDRESS: 192.168.55.55
  LB_PLEX_IP: 10.1.0.105
  LB_PROMTAIL: 10.1.0.103
  PROMETHEUS_PROFILE_IMG_URL: https://avatars3.githubusercontent.com/u/3380462
  # Network CIDR used for pod IPs
  NETWORK_K8S_CLUSTER_CIDR: "10.42.0.0/16"
  # Network CIDR used for service IPs
  NETWORK_K8S_SERVICE_CIDR: "10.43.0.0/16"
  NETWORK_MANAGEMENT_CIDR: "10.1.0.0/16"
  LOCAL_CIDR_1: "192.168.0.0/16"
  LOCAL_CIDR_2: "10.0.0.0/24"
  MEDIA_GID: "65537"
  CALIBRE_WEB_PID: "1061"
  WG_VXLAN_CIDR: "10.6.1.0/24"

