# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GJ32ZWl72pj45ZQtRLZqgpwpFw==,iv:iH8Ej75xKmLTluBuaiq0ABT5CGY244qXE46N2e/62Jk=,tag:gW4xvQPCcxsmV2Brf6bYIg==,type:str]
    XYZ_DOMAIN: ENC[AES256_GCM,data:+e4UfhmlA5H97FXe,iv:0NS9AyFQKZcsfHL2o0xyppYmtaVx5Gj+icPl4FDA/Uk=,tag:8zBBsbH++bToZlo7XCGVMQ==,type:str]
    CLASSIC_DOMAIN: ENC[AES256_GCM,data:bRYK1873,iv:u/u9DS89FdTs0AoZ7cghaNqtjGttYJCMlF6phnXNMcw=,tag:QLIHf3Wn1sxlUHbvShq4HA==,type:str]
    SECRET_GANDI_EMAIL: ENC[AES256_GCM,data:7xssgRxo5bZT,iv:V+0mWaSd+BxBzi+Rh3dXpGloE39VB2b/OfjQL0F2qMM=,tag:favUqYXsmpNLswYvP3VvBg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:oY4FKLyEbXGDDFP5F156xBWF,iv:hvfeJoDEWzLudA6EpeNtOh/fgp7adB4Rc/66pndYobE=,tag:zXfyHxizRFyT8Fno7l5Vlw==,type:str]
    DISCORD_ALERTS_USERNAME: ENC[AES256_GCM,data:9tGGGp1YEthZJ6spfQ==,iv:mKR8YcoWaP+4I5TuK91i7iEyOj6WT9jG2nM7s3Or+8g=,tag:OaoOzuppzb/1XPF6Fw4H7A==,type:str]
    DISCORD_ALERTS_CHANNEL: ENC[AES256_GCM,data:BSzuoSpL/tlm1y/gJKxxsw==,iv:OYrhWEPtdqWNwyaSiuNjs61rbnuoRq37VzaxxUQyBoc=,tag:Lv54fKPvp67fYOcyi0EBoA==,type:str]
    BLOOPNET_URI: ENC[AES256_GCM,data:c3zVdP76edxqgqcpRbJU,iv:f92hN4wlCIWiWn3VxZ3682FE4xEgx58dS98pueGbygs=,tag:y25R/zLEbErSBwR20S/2Gw==,type:str]
    DISCORD_ALERT_MANAGER_URL: ENC[AES256_GCM,data:5Q84pmO7jUaejIY3HP0IxCfwqxTFVUZ2b+jAXA57hN2PGWE91CFc/Km9TxdNJ6N3FR1Sb3bQ1HxnqGa3Wm01c/3xirfziJ6lsUcFnxC0MvqzvLaREbXOp4LMN9HrZjOSi2TC2y30PUoXgg7ujFFZ1l5VkfDtqZyI,iv:YNRbbP3++if+PKbRWLZ5o+oVwUMYDv6ncsqxj3VZqdM=,tag:sALgdla1TYAvnWxZXifn0Q==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:fwDGH3LiSiIppvgCenTljNbcBHifLpFHHClNeF4b/3zUhlQEvIfh44ATMVLqI2TN9aE6UzRQcKqzBNQMOBXUsy4EEQ1nPyirpdZqr4+NYh2Wcuv+6ZmHN924R+KNheyH15a/a18HLVAGrgG0gosIKWMpF+NEW3M7,iv:KcArWqy6Iu3TAqmMyL6JjiIaTXFqCjei9Bmj0Uhp4Go=,tag:1twfnXUGiipYBz8RxXQPHw==,type:str]
    SECRET_SENDGRID_API_KEY: ENC[AES256_GCM,data:kE470d8y44AKGFN0ZziDFGKgNz5pfM5ZyVHGik7/FqDS8qS207CdJuDnKyBZMplObqmxq9+S77WwVNBwr5R/ui2Xiabf,iv:DJ6YmuxqR+MqsI18id9XsOklnbiJg+iJyOqGd6/4oCU=,tag:KQznMbQnisqhRCab/d4euA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:v/wtaX5YAz/4DVV4SHcBKbIlhDV1qD9bVWZWiQCOVUV5rpuI,iv:WQxrOOMmy+2R4jANEXLBn7/WKUex9rFiRHc9NsokCzo=,tag:U/amzJVOJICvDcAY6PYbNA==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Cn1w86BH/uE2Hqlfz1taiSB6E1buCEqHTnJK763LxLqUXU3rvtKtyyn2OrrmVl5QL34=,iv:xydZAtcDyugzsotB0H90stShx2Rbm/ugyB/z/vveE+c=,tag:qZrI8O+8VN5DQYDQf/1zJQ==,type:str]
    AUTHENTIK_S3_SECRET: ENC[AES256_GCM,data:QCSYObQlYnmcAge8Q8p0NyLX78mrpK62TmVmBhrI8DuDbDfn,iv:o9g9TVULCwt3UzJzl+Vfcd5IMDkWGYNpaIRLFQ/JBbQ=,tag:hTWP9s3kYSOXFcH9x9hn1Q==,type:str]
    AUTHENTIK_S3_ACCESS_KEY: ENC[AES256_GCM,data:ur5CXOkjmj4b8iRgws1EjlCWdjkIe+0Bkd8LwoNE0WEfqSvO,iv:l1m+wQtOQMANdWLSl23FZNIfUKOWW8cKU0aTMB/+I0g=,tag:TMKVpx0wuOtViKYCzvCbLw==,type:str]
    KEYCLOAK_USER: ENC[AES256_GCM,data:jOkig6c=,iv:Qd9XlC7dZH9Fe3r/5HdxG0KuQI5o4oVElbPBoqYTM2I=,tag:w9iStXctxmGePf6VM65Llg==,type:str]
    KEYCLOAK_PASSWORD: ENC[AES256_GCM,data:nTgbtOH+kMbtiTyBZbRvEdlp6cvFoAUfz6s9H0gI83tw4c6f,iv:KoeCMNlmkvy1FDI/5qIniiQuQ85aHTLIAzyZORzu7iU=,tag:Lz0xIaVyLoWMwFAk2KCLjQ==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:aCOQJGmlRUE=,iv:hCkxU6EcdjPUICjR2gae8WSyWeQRCwgNlr2T/J2W4n4=,tag:jewtbFHCfmdMoKdimYjoAg==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:U3UBlmEMRKU=,iv:g9+ZABH90NbGPVI9IMktI/cEcoeCbOv5OA67xOcTmAY=,tag:hwcssUz1KootH0eNTfffsg==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:oJBMh277KUKBTJ4Z3uzVQ4vwuvZsRRv7Z4Vhak3SiUq3QRqN,iv:ycDXr9zv0mhcTyfu60b2nPxkYBNnFz/2d3P7Y2RMJzk=,tag:pQT1hYqkxGiNEFy9lmiB/Q==,type:str]
    SECRET_PLEX_CLAIM: ENC[AES256_GCM,data:Yj63Xhzyo9btTubab0/uxGG3IiGcXTEMpzc=,iv:meywlL6Oftvm3xKgdeihbpUgSWRU8qOC9DdNOKCUofU=,tag:GX2bIN/blWqDa9ne/NWJJA==,type:str]
    THANOS_S3_ACCESS_KEY: ENC[AES256_GCM,data:S3n4ysBH/Tjm7jgJfsod,iv:w1j3ksYdMGzltQVW1ZHJjTK8lFuvauQVBT9FcIx/J3U=,tag:40I1bnnqStEVsrehBOFC+g==,type:str]
    THANOS_S3_SECRET_KEY: ENC[AES256_GCM,data:FtQ/afyUGtSR1rqduSfbug07HNaQbzhSrvY/5l9tQM1xDiAMmVXSvlqUQFs=,iv:LXaMjq8VuI1e4Yh8vz7qKgR5cX0GQyRQZCF/96xX0zI=,tag:rg+oZOAH55XWwlVj7j4v/A==,type:str]
    NAS_ADDRESS: ENC[AES256_GCM,data:1AroKBBqP9M1aHWGdw==,iv:8XJ0vtZipNabbgNYV4u1XlYb91+c9tqSMxypNwAtn7Q=,tag:qJv1ahtPRK997SurwEfnDg==,type:str]
    MINIO_PROMETHEUS_TOKEN: ENC[AES256_GCM,data:FmslXkcOA7sAg7BqeK/DVkddrCvTzjB1DLijjcoWzfo3KmkxBFuYCIdbi3cGGSevF1eG7VsgBMOjDQO3mhpTHUDwk4D6pWrn/WWJ5VnMOb+HKO48MM000uGZofWUHsuPcmMXOMsWYfpA8BuIKIvPGS+d+YqgH0bLx2SXaPyoq0ityboESC81d51YuP8BXS/fD91dCaB9SDfnfom/lAx9gJ0H2CxBEJaLQpWg1N0Nr51U3iZ1iQxZExlQmHWPLGqu,iv:Lfuu6A942jgk/oeao17IJUc+9QDlCszQFo3lY48ysbc=,tag:s9H8iaum3cbdmo/pYbkJXA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:6JbdJ36wU+DlcdPdeamCxJl9+c0961tNlVOatNrkltw82ezFKgnh8OqBZAo=,iv:YVsmLdkJpNGNxtfrft9Mqoyr7HkepzhbPK2dH2co3tg=,tag:6R6zGtoeKfg6upD1jGUWQg==,type:str]
    GRAFANA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:RCdcCGgg/l+aK6hR09SyTYgGQR51aE6DwhRo23XggS+ESDzhzwekDA==,iv:ukVVXHqfdgIi5R3shjkoGdLbajG9Uskhhu2A72LjmUE=,tag:+rVhZwnJbuUG0OvOdlfUlQ==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:LcaIBwaCOzf2Xx60+z7oxFnZBzP7csRMFgg/0HKCqaN6T4LIlfmtf2Jt9fsSEMEw+ZsCIRJyME7HkCI5Aoc0lirKaf9LdZOHOMWUvQL4Ymirc3yMhyPI8FvrSjcDu2n7xzRbcHEOllJfoY8CItAlNyORa5rkGCuLMZ35i+3fOCQ=,iv:EkBEs2Gfj/RIEdqRI9CSkR49PdxIlACTKoz5hOY5ow4=,tag:9RWXmj3ofaCsN99vGbNq1w==,type:str]
    VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:RaoxGEQ=,iv:9K8gBqK2/9AHs8qfXZToupjU3ZikJ5WMDTmU8jFBVAY=,tag:cVptuXpcoLVYyerIiSSXww==,type:str]
    VPN_GATEWAY_VPN_PORT: ENC[AES256_GCM,data:IHySaw==,iv:75F/yl2aoovLQvAuGSWzJSGMtH8pCpoibNBekjAhkM0=,tag:RAGBFGUpvuMVnLBzZ60GtA==,type:str]
    VPN_COUNTRY: ENC[AES256_GCM,data:6rJq,iv:wNVHqMGN+VhIqqC8GrsvE45K5QDgKU3PVUlRUusJR7w=,tag:ARjKBqiTACQ6fWwT/C8B4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTUhhM1dRMzBDYk5NSWMz
            WTExNnl6Mk9lNG84TnVsMDU3bE41K3lpS1JRClhhMWlqOHYzejQ2T1pMLzRCaFZ5
            NGxGdFFIbXB6cDlUR1MrR1RIaHpaWkkKLS0tIGJReE5nRnZjNXlIMDFLT0FwVE14
            THBYZ0YzZXBubWZmYmlpdm1pd1J3MTQKDl+Dypt3JwmDVO0FxW3WnpT9brEWyHQL
            LWKQPNsxEAfn7j/8TmLt83a8XR/RJbxlGgdutG3ilj+SPT+PWHISiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-23T03:05:59Z"
    mac: ENC[AES256_GCM,data:oCf7uC25qfAIgGUQUbz4YSH2vRDON8WveRT6tUyR73jWBvDTwq2eauLEHyBN4mGpLdVWm1Vq6lL5jslpfXCTvqzIa1xr5NCeeo4eNhl8DpxhvDInMhrW0zOZkPp0+aIR84Yw9hOd6GAZ2jdkPS07jVonoEyEOyl9KJaylAa68SU=,iv:C1xrbrI6DPvkWt4fwqiJk/TWWzmkdeHrsEG14DwTX8M=,tag:3yHeRN7sHcczYOoklL638A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
