# yamllint disable
apiVersion: ENC[AES256_GCM,data:IXc=,iv:US8zEYfKui9TD3FBvwZO01aZgssCSxn0BX0clkqVzP8=,tag:BmJqRNgYtSeP1VyEViJLDw==,type:str]
kind: ENC[AES256_GCM,data:viTCEXzV,iv:e8FiRZlF1DCPfV1Q07xLedSSgJZSzM8ARr1w4F37pMQ=,tag:clk49/tP2Zf+5mWNz46xxw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7KQStjjeUr7EEpQhLyNh,iv:RYYRFgnYhtHD8AhutVa7mQIupx4FI2zXpJgTwD9OFks=,tag:n4ybz2GTs2FcmGtjV32Atw==,type:str]
    namespace: ENC[AES256_GCM,data:8HARfGYv3sfnkwA=,iv:r6bRkT2acdoInpUIko9YsOymRXbSRHMqZHFoV0lv9Po=,tag:UwVM66q4T1WixtTycaZ0NQ==,type:str]
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KDy7WaL69vULeJn8mbGGRm2f2Q==,iv:fOMtIFnMBQusxvs9OyOyh3zwAQvBBrkjjiWM3iKEZYU=,tag:mKSjWG2CMlH3w7sn7YAXHw==,type:str]
    SECRET_GANDI_EMAIL: ENC[AES256_GCM,data:OUZw5dZussMR,iv:mibCGOiUO/bQQMBE7Kt8YkO7bntj6SebJT+ZmFjlDHw=,tag:TyheTr4XNggHtBbzZdW9WQ==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 1739B455D8162E8ACC070B6C818FDD02AE117F11
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwTlN39ypZ1lAQ//cnPRRp4JKK41/iV+6oSvoTMZCJdQgmZmF327cneXHSnX
            +H1f5V8+wPitZ3yMdbH3fLVCIkzw555KiXQxP2NQrwv+oH8g6ILoZN3Vd2b3MiI8
            LWtqojuai3uiPGSbDgX/PluPnNgLv61jGNusE+v5psqYCebvW2EICGPd1JL9GpFc
            QP2e48GeTm+ll6dMbYbTWZl3fZo0Rp0Cqw7jwCL5d/NBW79MPAT0mjNnYXoz5C0o
            x9W/1B3VpkQN8lUp48BSwdduRUY3SyS73XkBbA6uQSqvHVXRKJfzAVaPo/ruguQ5
            qCuoXsj4w7L2FRlpCdIRZTbSwwz6S9SPZIOpMucCLpmi2fTkvlBTBKZiFFRVvvpN
            5PP0VuJTNlSZ1WfLKsBf6CEkQ2Fl/jiuWgIC6+FZ0BE4K61bNNa5wtLKkdqRWHLf
            1mXkml4Pyfs0QJZfxVyLU9XGelwxgUYpjH7ul7uZz6iwnQKvu4jcAc28MCaPwwKP
            Sp4Ui7tKnm0RSxJ0Xk64e//WO5SH81wwi8zvDrg0hzWZxsbKkD3TPDuvoBOwAJT1
            IDoI/Csbo10uYwgvdJuq+bYvdnLpNolxaRdoa+Y7LTB62LmZ+VIBYWfIJFQfPJcy
            ex1QYDGKTA2d/JtbzuwI1qR7mKPW2oEIJy3vY4kjsCi62/4AST/BkY7rrozEgLvS
            XgFGEkpaO+azKxUD9L2CvfOqmFWtaUNaN/wjlKRZuMt6wraHk7/qgpFR6WyALTny
            wLS/XlQNxSJ3q4JE+udie6qSqlwV2uh6/a7WymNRXAsXchuvrVis2m5hw2G41xM=
            =Uaqw
            -----END PGP MESSAGE-----
        created_at: '2021-11-24T20:25:10Z'
    lastmodified: '2021-11-24T20:25:10Z'
    mac: ENC[AES256_GCM,data:jleCghvH3yO7jrCc9nAUX+ShUlEAutAxHGl4ZMTMe1turNqSz6Jj9202sJLEhaPLNmajJxeo7im6F71mKkJRBSoGegMq1jiY+ueUW2jrZ3czw6PtQ/hRv0HuFqttslpIgPtX3sWssVd+2jA8roGdbArTj9tAwi4rA99LOoOT6M4=,iv:6nAY4kHnlM+P8Hihm6kzuNxu3x8wvT+zsLB6wlsdo1o=,tag:4nMeywwImDp7zPrtO3Zpfw==,type:str]
