---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-v1
  namespace: downloads
  labels:
    k10.kasten.io/backup: "true"
  annotations:
    pv.beta.kubernetes.io/gid: "65537"

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
