---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  dependsOn:
    - name: vpn-gateway
      namespace: vpn-gateway
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.9
    env:
      TZ: "${TZ}"
      PGID: "${MEDIA_GID}"
    hostname: qbittorrent
    podAnnotations:
      setGateway: "true"
    podLabels:
      setGateway: "true"
    settings:
      automaticPortSetup: true
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_QBITTORRENT_ADDR}
        # For BGP mode
        # externalIPs:
        #   - "${SVC_QBITTORRENT_ADDR}"
        ports:
          bittorrent:
            enabled: true
            port: ${VPN_FORWARDED_PORT_1}
            protocol: TCP
            targetPort: ${VPN_FORWARDED_PORT_1}
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          hajimari.io/instance: "bloop-quarky"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "qbittorrent.${XYZ_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls.qbittorrent
            hosts:
              - "{{ (index .Values.ingress.main.hosts 0).host }}"
      api:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
          - host: "qbittorrent.${XYZ_DOMAIN}"
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - secretName: tls.qbittorrent
            hosts:
              - "{{ (index .Values.ingress.api.hosts 0).host }}"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      downloads:
        enabled: true
        existingClaim: downloads-torrent-pvc
        mountPath: /data/downloads
    podSecurityContext:
      supplementalGroups:
        - 5600
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 6000Mi
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: esanchezm/prometheus-qbittorrent-exporter
          tag: v1.2.0
        env:
          user: "${QB_USER}"
          password: "${QB_PASSWORD}"
