# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
stringData:
    api-key: ${BOOTSTRAP_CLOUDFLARE_APIKEY}
    api-token: ${BOOTSTRAP_CLOUDFLARE_APITOKEN}
