---
kubernetes:
  children:
    master:
      hosts:
        slowpoke:
          ansible_host: 10.1.0.87
          ansible_python_interpreter: /usr/bin/python3
          kubevip_interface: "enp89s0"
        k8s-1:
          ansible_host: 10.1.0.88
          ansible_python_interpreter: /usr/bin/python3
          kubevip_interface: "ens3"
    worker:
      hosts:
        k8s-0:
          ansible_host: 10.1.0.68
          ansible_python_interpreter: /usr/bin/python3
