---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: classic-traefik
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`${CLASSIC_DOMAIN}`)
      services:
        - name: classic-svc
          port: 443
  tls:
    passthrough: true
