---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: classic-traefik
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`bloopnet.${CLASSIC_DOMAIN}`)
      services:
        - name: classic-traefik
          port: 443
    - match: HostSNI(`home-assistant.bloopnet.${CLASSIC_DOMAIN}`)
      services:
        - name: classic-traefik
          port: 443
    - match: HostSNI(`traefik.bloopnet.${CLASSIC_DOMAIN}`)
      services:
        - name: classic-traefik
          port: 443
    - match: HostSNI(`ombi.bloopnet.${CLASSIC_DOMAIN}`)
      services:
        - name: classic-traefik
          port: 443
    - match: HostSNI(`portainer.bloopnet.${CLASSIC_DOMAIN}`)
      services:
        - name: classic-traefik
          port: 443
  tls:
    passthrough: true
