---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: classic-traefik
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostSNI(`${CLASSIC_DOMAIN}`)
      services:
        - kind: Service
          name: classic-svc
  tls:
    passthrough: true
