---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: auth-ak-outpost-dash-admin-proxy@kubernetescrd
