---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: xyz-auth
  namespace: networking
spec:
  chain:
    middlewares:
      # Note this requires cloudflare proxy
      # - name: cloudflare-ips
      - name: auth-ak-outpost-traefik-default-xyz@kubernetescrd
      - name: chain-no-auth@kubernetescrd
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: bloopnet-xyz-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: auth-ak-outpost-bloopnet-xyz@kubernetescrd
      - name: chain-no-auth@kubernetescrd
