---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-no-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: networking-basic-rate-limit@kubernetescrd
      - name: networking-secure-headers@kubernetescrd
