---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authentik
spec:
  forwardAuth:
    address: http://auth.${XYZ_DOMAIN}:9000/akprox/auth/traefik
    trustForwardHeader: true
    authResponseHeadersRegex: ^.*$
