---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: keycloak-auth
  namespace: auth
spec:
  forwardAuth:
    address: https://id.${XYZ_DOMAIN}/auth/realms/Bloopnet/protocol/openid-connect/auth
    trustForwardHeader: true
    authResponseHeadersRegex: ^.*$
