---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.yaml
  - rfc1918.yaml
  - redirect-path.yaml
  - forward-auth.yaml
  - rate-limit.yaml
  - keycloak-forward-auth.yaml
  - admin-auth.yaml
  - xyz-auth.yaml
  - plex-add-web.yaml
