apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: networking
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowOriginList:
      - "https://{XYZ_DOMAIN}"
      - "https://{SECRET_DOMAIN}"
  #  accessControlAllowOriginListRegex:
   #   - "https://"
    accessControlMaxAge: 100
    addVaryHeader: true
    stsPreload: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    hostsProxyHeaders:
      - "X-Forwarded-Host"
      - "Forwarded"
    contentSecurityPolicy: "frame-ancestors '*.bloopnet.xac.im:*' '*.xac.im' '*.quarkynet.com' '*.bloopnet.xyz';"
    customResponseHeaders:
      - X-xss-protection: true
