---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    configuration:
      startTime: "4:00"
      endTime: "6:00"
      timeZone: "${TZ}"
      notifyUrl: "${DISCORD_WEBHOOK_URL}"

    nodeSelector:
      kubernetes.io/arch: "amd64"

    tolerations:
      - operator: "Exists"
        effect: "NoSchedule"

    metrics:
      create: true
