# yamllint disable
apiVersion: ENC[AES256_GCM,data:9uI=,iv:ZhtjuhlVtHb+NkzqFPBBSvV4vdByfZG9C7XK3yGj+uA=,tag:lz/GL7z+grEgGvPzFkgT5w==,type:str]
kind: ENC[AES256_GCM,data:WoO9DkXc,iv:XoRNwUgDoH7w2RuvbP5rd2oeuDYcG/l1xUUgapfEabk=,tag:rocgAFCaBTY8aJnDfK3e2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H8LnUc6dZNu8digSR5mNljTn,iv:TPMgYL4atM1/Ks8F7ng0DIfc2FKWIO5f6j/JEdDwHvQ=,tag:woP+6TVZg7MBwbjfrMOK6Q==,type:str]
    namespace: ENC[AES256_GCM,data:XdbfJdYcP892ZQqP,iv:pxYy4w9qa6aVb0+JuDpxgM7Od8OJc8PGgzrWf2TlyGo=,tag:I2XBseEcZrtw5tuaEcZ6Sw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:fq7cdyIf+1Rvv61OhHEHJQfwMa+xQR+A,iv:C0VNTsTbBkinIBe8dr8N7BxU0gGhEigBfKuXVmOJnFs=,tag:U/uvbhXMLJX/SU89mxEpjA==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C3FF78E5BF483EE816D78FAD1A42C338D23CA1F3
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxRAF+S9s+QEAQv/SjnRS3GfGMPX03rZ3MFfNOsFm4+olttKVMXfApIbQSE0
            yuOi53eDZNazQBfDLFBgs7Z3MUjT1ohGXD2WbpapC8MzKF8SIRVZwKsSc0DxZ1do
            nLKox0WhHl9lQE0K1gXPiJ53rKTu/c8Ma9ScHIU6RV8i2/gM+AjHvEORMjtIpOWv
            +zc42yk9xBJlZ+St/spuNRVyhQ03DA5+eLZVnN/rVl0FVYilR5s1q7g6282ggBh5
            2SUv2QcMfaBgY2A2fX90kTMSTleKlqud75wexZ8VBRkcdJBGiTmbkOrxNnFc3e2j
            FyMF+D4gHv5C2+JG08Uf6Ckq8X5mDjS7qgIC/8tVTsNwJ+Q/uQkWhSXRJPMeGXgn
            9RBnGWn4FzmRuPaQmDCXpzQV2MfOf0LQDUdNm500d2tJB9nFxzS3H5ELSDTX4OWy
            5tmjWoh1OieTm6XS70TrSd4T2K9Ja6/U76Jq0tbVfnqlAYkSz16Kni9b/iFB061Z
            3LzaaW7Sdn6l5+xwI+SO0lgBCeYKQ5hdm9E095nil84ZI5zM3QfuV+dAgKiOc0rw
            rnquhE4A5cKHcbNAtDjeooYG+wnsuooMVzgAXBKHzS7jyFvsCUhUVizL3Rijsrzz
            uVVdwN1hcKy5
            =igGC
            -----END PGP MESSAGE-----
        created_at: '2021-11-13T20:51:05Z'
    lastmodified: '2021-11-13T20:51:05Z'
    mac: ENC[AES256_GCM,data:4UXv7icY8PSM9FkndB9hrLsTb60vf9KndLT5YEtDWgKSTjsWrlfjMZE8ZvzoSdbSXVgpdGSqn8fXIQmGWTjMLWK22+Jogl8TqB7U7YYUSf/kgz0XkNR8NkfrbvurJy7l9+12uNfwqcsxBJOywbbxlozxoqdnZSzeMKIza6SLwhc=,iv:8Ayg+x/9Gh/+a004Ck7Vl8xdzBWvdyor8yZ1qqtIJcc=,tag:n0n52IRULwKdReR3AzmB/w==,type:str]
