# yamllint disable
apiVersion: ENC[AES256_GCM,data:Yso=,iv:PXYYvmMGnnHmNNi14L6PGb6SenhEgH1oSZIS2AF7DQA=,tag:ziEWWcJNFUUQQTEcAfgbKQ==,type:str]
kind: ENC[AES256_GCM,data:1VijYf71,iv:Ltg4kHwUi7gzIiNtnrr1jgmzuW4DHG8A6ik06qCOdSs=,tag:FCICtMMeUGszyQ34xI2q6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B9NWs9pLfxX/AKTXxY8Tlamj,iv:4F1gvRJcS7AbbnlIicrzOLe9zR1f9NWZtmjVczvP3CY=,tag:gnOzOqQUyWoBDZ1OBAAD7w==,type:str]
    namespace: ENC[AES256_GCM,data:linPML2GAnAX7Ht0,iv:p4iz0hvmNa81zu9sAyqjoFnszYFVT7AOPBc/luoZxD4=,tag:6NucgM+NP0p/jyfvZM/ZQQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:OhOlSOOqr31JEsyl4MHNMy21fBEl1oQf,iv:4CKNR0oKHf66Md+qDx9NvWV90Pj5Z02ZSGEH88yxS00=,tag:+LdVMjzCioaxdkglhMW02g==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C3FF78E5BF483EE816D78FAD1A42C338D23CA1F3
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxRAF+S9s+QEAQv+Kq0yY40lTjLX+9wyfc37YmHsNy8V5hvqNLU5zVQgnULW
            PW79gMbr3F/ooH08M1qNGDUsAEb8alWTmZa4l3OxQq+DqrfOj3MQM+4jtnRo4nuF
            c4jjdwFg/FHN7k4qpGq5p0Ti6EcU0X4IYWC2HCsN3Q5Geg0717K1bzc4hktcvgJl
            ER/4kq5Rwf3Qyrs5MMj2O/UHSaqhyL0li475J7VEJK+H+B6ePkYfbaEwnYvLyKKb
            Y19cjL21zxtrKfWliAT4G/4nUJQDSu49btsZshmI4fuKnfqEwvrRHRw44FFvaSBc
            QwGoZ0aBUUj3GXuYT8SB+9FFHKqq/JcuBBdySrbFTGy3kRejF65UqgmWQJ6+wxbO
            HxgDhjIvmlL7ZsDTaYcbTADrEc6Y62vtj+BTVPqmNUR1zs6t3RhO9KyVolmlMuf2
            yA8zuhALrzWGWdm493VFIqOOY09I7EJ/yIHXOXWVKRpXlH5n6lQknJuMjpMxYKbO
            CyChCQFu70DVu2YBdbmc0lgBZgXlTJu6OFGYFcgO0tjRGcqvduIZ64xCHEBr2D9x
            yC1vOHmIMvxgpafBIe9QEWMeWac+SKwm/tud16Kc4wXCny5aWrSE39/nwK1OMAN7
            G9BJ7OQi+qjp
            =QHn3
            -----END PGP MESSAGE-----
        created_at: '2021-11-18T01:53:52Z'
    lastmodified: '2021-11-18T01:53:52Z'
    mac: ENC[AES256_GCM,data:FMMHsTppRh6r6uAoi+N/Qa6UwMu3X2wt1poJXhzs3JJ0J6ebMlaJvTILAYnRmbEVPPeRfkonp5rgL7N/Dljut8eaz2DYdD6DPFplqWIIfqHG5DquilN49P2RgU4zjl+pZScyP4ppY7mAPAFO3Yv/0kI/YmtJeKewCiZOzlPkm2o=,iv:X795+JeBQiMljI1bE4pKVUzhEbwJGMFTZa+/iOF5Cy0=,tag:ItXAd8xN9YWakGbSd74AKw==,type:str]
