apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:YwVMcRcyCyvIbdjbjCqP/96YbtEajvx4r/0zXMTZszf+moanUg==,iv:pjECOkFxefxpDhKsbiO8X1+psUzXw1u1zl4zxE0fCTs=,tag:M9k6rHtn8ta32yXkpsoWVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-11-27T17:36:16Z'
    mac: ENC[AES256_GCM,data:j8OXNurrZHbLwKmKX45GM8dY449uGNbPFDXjvm/bAkxIsPcywShLvdLMNTU83NBMdNwCspnerKhx0W95+tPqYfl7qxVm5LZtQ/PvzwabL2jiBSsGx7xqAe3qkOmbIvE4Hny93FdphZD5XG25j+v8RfHI3i0vYTtXgav3IaNs5Qo=,iv:3j9sHqqU4yYVlhf390EgV2n+Bka4KAnoQognV9CWMEs=,tag:KU+d3B7Hz+/UdQwU6/Kudw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.4.0
