# yamllint disable
apiVersion: ENC[AES256_GCM,data:o0Y=,iv:fiHRYpHvGk33ztp7OGTuyqrQVmnxBDvJjrZhVN5vSGI=,tag:DkiScnRM7wj0lW6AaB4ZTg==,type:str]
kind: ENC[AES256_GCM,data:OQRsAgzW,iv:4/raMFP6xRInhyemHoyX8xcGPhlURyhrn9HDokMQIhc=,tag:EkC6K+BdInGONYVv3i8mWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TDD2jix5Js9Tk5SL6+NhmWgo,iv:7DVU5XogQnGerUTUMPGdRsW40HWcEOr1XJbpOBhkG+o=,tag:F0z1h4ILy449/X6RdFe46Q==,type:str]
    namespace: ENC[AES256_GCM,data:vzZTX2CI9pZE+vW9,iv:XkugkNCCdyxSBnobJ3g+3ndcVSeceNMQzhwk9iypjiI=,tag:mO/8a7h0AIbeKOqJL/1D+w==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:Eyi2ZJ/z2+E0ilUnG0dJLvemQXzDBMyJ,iv:YfupjcSNiHnkJS6uVuD5T/uoRWw/yfHZUpOospVip28=,tag:LsS4Rc6IbzP1F+mcVy6uVQ==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C3FF78E5BF483EE816D78FAD1A42C338D23CA1F3
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxRAF+S9s+QEAQv8DXvdpZ8Oigd7cWwt5998ILmg/gDN88R9N8CJhCUp9RVb
            WvQk9MNt0BA6nkkXAzqry/1ALtTkB/SCMPpUzEalolGaKTHujMTMeEMKattUBN8Q
            sb6E45lzDNOeS8ZdpyvDuarUt28OcZOzy7rIoMJj5CWoPCJctQ9vFaQujc97J+DN
            udrsCVuapFqH9raJ33tFUX6dskWOuH+PmaFMj3M72aUcHRw3ZE52qJxACeDROe64
            iXsY1z6lJVdNJR/2Co2QFF7FsKtXPPJiUW1QSJhWAmqcMKAQkq0Og68kFo3qLBu+
            1fdflejoq4F9DAFGbkS2S+oS+233PDoR8Z9aTSrbN6lZ5WAJKTNzitRVNLMxeIsm
            SzFv6IGG/ItIPXm4RFs/bZ6Lvwo7efp/+sie94iOnA+devobJFOGU/Cap6fYWVG7
            mCCtw28yfgAangDwcSsctNoVAeO0ZA9YKeiN04QS7Avbmtwi2b+IAqNo5Z64Wakf
            julS7gCjWu8J1ubkv5pR0lgBlPdlArggH8gOGbq8QA3OONoSawL36YjnHp0LjHnt
            Mrn4bvEwJO6RI4XO7dihHNzFf/nwwx89dFPtROxx0DOuwbPrTZOZ2ZLQ6lAo4NFb
            FTfskJ4YQr2M
            =WyCU
            -----END PGP MESSAGE-----
        created_at: '2021-11-14T04:09:59Z'
    lastmodified: '2021-11-14T04:09:59Z'
    mac: ENC[AES256_GCM,data:dQOwYw9FinTQKdXwFooarnM95a6h8OdjMw5RBoxdmpEATEt6156Zk13Qru2JiJ2J9y7n8AjUdCC7BVfa/Hzthn0gafjg+h4hjdhwZAw1hdDxXEWH3KMihxtMxb1s3tH0UPFLn6ug1njFUgtBbtuo0cgITLgOVW00/E1DoscATa4=,iv:VfUJx52K8FF99tt7xsZqqZQAJcwnB42CM4SY5m1knuw=,tag:5Ar1meQPIbg/dX1biy56DA==,type:str]
