---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emitter
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: kah-common-chart
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: emitter/server
      tag: 3.0
      pullPolicy: IfNotPresent
    controller:
      replicas: 2
      type: statefulset
    nameOverride: emitter
    podLabels:
      app: emitter
      role: broker
    env:
      # - name: EMITTER_LICENSE
      #   value: "..." # <- Provide license
      - name: EMITTER_CLUSTER_SEED
        value: "emitter" # or "broker-0.broker.home.svc.cluster.local"
      - name: EMITTER_CLUSTER_ADVERTISE
        value: "private:4000"
      # Values are 'inmemory'(@default) or 'ssd'
      - name: EMITTER_STORAGE_PROVIDER
        value: "ssd"
    persistence:
      config:
        enabled: true
        mountPath: /data
        existingClaim: emitter-config-v1
    service:
      main:
        nameOverride: dns
        clusterIP: None # Headless service
        ports: # No port is actually needed
          - port: 4000
            targetPort: 4000

      broker-loadbalancer:
        primary: true
        type: LoadBalancer
        ports:
          http:
            port: 80
            targetPort: 8080
          https:
            port: 443
            targetPort: 443

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd
        hosts:
          - host: &host mqtt.${XYZ_DOMAIN}
            service:
              name: broker-loadBalancer
        tls:
          - secretName: tls.emitter
            hosts:
              - *host


    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - emitter
                    - broker
            topologyKey: kubernetes.io/hostname

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
