---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 10m
  chart:
    spec:
      chart: k10
      version: 4.5.10
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    eula:
      accept: true
      company: ${XYZ_DOMAIN}
      email: ${SECRET_CLOUDFLARE_EMAIL}

    global:
      persistence:
        storageClass: ceph-block

    auth:
      k10AdminUsers:
        - ${KASTEN_OIDC_ADMIN_USER_0}
      oidcAuth:
        enabled: true
        clientID: ${KASTEN_OIDC_CLIENT_ID}
        clientSecret: ${KASTEN_OIDC_CLIENT_SECRET}
        scopes: "openid profile email"
        providerURL: https://auth.${XYZ_DOMAIN}

    # Specifically for logs visibility
    clusterName: k8s

    grafana:
      enabled: false

    ingress:
      create: true
      class: traefik
      host: &host k10.${XYZ_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: ingress.${XYZ_DOMAIN}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: network-rfc1918-ips@kubernetescrd
      urlPath: k10
      hosts:
        - *host
      tls:
        enabled: true
        secretName: tls.k10
