---
# Increase memory limits on source-controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              cpu: 1
              memory: 2Gi
          args:
            ## Helm cache with up to 10 items, i.e. 10 indexes.
            - --helm-cache-max-size=10
            ## TTL of an index is 1 hour.
            - --helm-cache-ttl=1h
            ## Purge expired index every 10 minutes.
            - --helm-cache-purge-interval=10m
---
# Delete the allow-egress NetworkPolicy
$patch: delete
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: flux-system
---
# Delete the allow-scraping NetworkPolicy
$patch: delete
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-scraping
  namespace: flux-system
---
# Delete the allow-webhooks NetworkPolicy
$patch: delete
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhooks
  namespace: flux-system
