---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - config-values.yaml
configurations:
  - kustomize-config.yaml
configMapGenerator:
  - name: botkube-config-values
    files:
      - values.yaml=config-values.yaml
