apiVersion: v1
kind: Secret
metadata:
    name: botkube
    namespace: monitoring
stringData:
    discord-token: ENC[AES256_GCM,data:FlzspA==,iv:fvGJQyNs+Co20BBHZhVwGTdXrlXZtGZjjJLL/t2UIqw=,tag:SXolfSl0dPiLVxEkGZZkzQ==,type:str]
    discord-botid: ENC[AES256_GCM,data:7EXYpQ==,iv:wc7q9QqN3dwchi4FGak1fSWDGbND9nUdh2x9/h1yLKo=,tag:jMaSzYvBFQAtPXZnRBrdhQ==,type:str]
    discord-channel: ENC[AES256_GCM,data:XQtvtA==,iv:Zm+voIUjQEZ/N+7X9IcyVNmfElrKDp5rM+zlDL/0JIA=,tag:gbb7zmzE2HIHgCy44Mh4GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUW5vWTdEaHFQa3lvaS9V
            Q2hhSStlSStSc3YrM1ZQQ2JQRGdIdEF6VHp3CnBXSUs0TnhUbFVqbG9VRDNvRS96
            SDZVeThjZjF0Ym9yaEM3V2ZvaWdMYk0KLS0tIGo1cGx5RTlpOFF0a1RRbWtGam92
            YmtZYlVkSUlNYlNUMDdQalNXbXIrSzAKgKCaYpG16jzptSWD+6e/5JRzZKENEZd7
            3ipj0vr4jiAP+4cJAax28803HmzL64rwiOQTAVFugmfaFt9SWl52vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-03T03:31:58Z"
    mac: ENC[AES256_GCM,data:d0iS1706/HfpMyW5lRe0ymWcGpAKLNmqFCUjeJpjFhhfxgfU63ZNS6dVbeD5WOcfrW8hwWLyUOrHlR0W/tGwuoEL50xRWgddKy2P4GiYLTR14rnBVGVzGQ+jc+AnNcQGbDkeR+AhiKBJSr2GRFUH9FD8blNxRrTLH4tCmbt+9So=,iv:LWkElkA+I3LM6nPRChgHi+a9E0YYngfajeZqXqyKBlI=,tag:lJMsyMP3HS7Lr148E3/8rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
