apiVersion: v1
kind: Secret
metadata:
    name: botkube
    namespace: monitoring
stringData:
    discord-token: ENC[AES256_GCM,data:0/v5r4cb5cZm9J7/gs/1giQ6ZGbSGiyRiILbB/jpWskYsg2Noqzwrk/KHUTeYgVldrQv9D1Xd27KXaE=,iv:Vc4qKqyYnFHnRTc7D6yyyMXxDtOqYYBLOUkIcoxtamM=,tag:xsSHJ1yf56kEyjClVl9wTQ==,type:str]
    discord-botid: ENC[AES256_GCM,data:e8jhq8osQVOKQnxPimD+gJLP,iv:EEsHB2LD9z/hEdDUevi9nLWxpFDfQhM8vKR3ThgeIQs=,tag:vUx/rLEs0HjPVtL5p1hxOQ==,type:str]
    discord-channel: ENC[AES256_GCM,data:JLNO1JZeVUGmWnioDj/GsrZg,iv:RJx6Ees1VnoP1E/xNuE+an6pSTBj8rKu4x38IX7hEyw=,tag:EOpltpvt/xv0jVSLzpOeFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMGxQUUo3Vi95Q3R6SytY
            azExZkR1VjgrREppRFJBYWl5NDRhcmRYcnlzCm94enF3RURJcDdDM3QvS21OM1Zh
            Q1I0M25Ncjd1aEEvRkJHQzYzYm5vSkUKLS0tIFpUN0RpYVA3bGU5R2c1N3ZXMEVa
            RmJIMCsxaDdZQU5PZk9TcCt0QlNSSG8K7lq0AB2rIiAhVBmoTeuYE31Jm3kAxsZh
            yvDk9PcxMKMj8eYQ7JbBpbUTgzO1aIx/vfTvCetAAn+xGBrx68fftw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-12T04:03:06Z"
    mac: ENC[AES256_GCM,data:valHMpqnmF3Uuu95mrecJl/biG9ZVHWfFHmGQSu+MIxqgb9o2kQlm9Es8Ki2kbtOQ3uvaMcKO+fhbQ2okMN172WKt9+ArKa1qqChcJSJJC93INXRFWvS9nhoIv+s0OcUGCcNeGVwIu3QswLbJzdD4YxeS35LOBPW1EjPqIAlg4o=,iv:eT1HspZdCZadR3JoLNLIhlVOwd70/kthgOE9hR9AJW8=,tag:PlBifHpbeqXmCIzz3/Wfhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
