---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - auth.yaml
  - metallb-system.yaml
  - networking.yaml
  - storage.yaml
  - monitoring.yaml
  - media.yaml
  - vpn-gateway.yaml
  - velero.yaml
